#!/bin/bash

if [[ $# -ne 1 ]]
then
  echo "This script exactly one argument. Exiting"
  exit 1
fi

echo Running problem "$1"

mkdir -p results

relative_problem_path=$1 # relative "Problems/ALG/ALG001-1.p"
file_path="$TPTP/$relative_problem_path"
file_basename=$(basename "$file_path")

output_file_path="results/$file_basename"

epoch_before=$(date '+%s')
timeout 120 isabelle tptp_metis_lifting 10 "$file_path" > "$output_file_path"
if [[ $? -eq 124 ]]
then
  epoch_after=$(date '+%s')
  echo "% OS TIMEOUT after " $((epoch_after - epoch_before)) " seconds" >> "$output_file_path"
fi
