#!/usr/bin/env bash
#
# Author: Jasmin Blanchette
# Author: Martin Desharnais-Schäfer
# Author: Massin Guerdi
#
# DESCRIPTION: Metis tactic for TPTP competitive division

PRG="$(basename "$0")"

function usage() {
  echo
  echo "Usage: isabelle $PRG TIMEOUT METIS_VARIANT FILES"
  echo
  echo "  Runs a variant of Isabelle's metis tactic on TPTP problems."
  echo "  Each problem is allocated at most TIMEOUT seconds."
  echo "  For a list of METIS_VARIANTs, see slam/slam_tptp/slam_tptp.thy."
  echo
  exit 1
}

[ "$#" -eq 0 -o "$1" = "-?" ] && usage

SCRATCH="Scratch_${PRG}_$$_${RANDOM}"
SCRATCH_FILE=/tmp/${SCRATCH}.thy

TIMEOUT=$1
METIS_VARIANT=$2
shift 2

for FILE in "$@"
do
  echo "theory ${SCRATCH} imports \"SLAM_TPTP.slam_tptp\" begin \
ML \<open> Slam_ATP_Problem_Import.metis_tptp_file \"${METIS_VARIANT}\" @{theory} (${TIMEOUT}) \"${FILE}\" \<close> end" \
    > "${SCRATCH_FILE}"

  isabelle process_theories -o "threads=1" -O -U -d "$HOME/git/slam" -l SLAM_TPTP -f "${SCRATCH_FILE}" "${SCRATCH}" \
      | grep --line-buffered -vE \
          -e '^Running Draft ...$' \
          -e '^[[:space:]]*$' \
          -e '^Output \(line [[:digit:]]+ of ".*"):$' \
          -e '^val it = \(\): unit$' \
          -e '^Finished Draft \([0-9:]+ elapsed time(, [0-9:]+ cpu time, factor [0-9.]+)?\)$' \
          -e '^PROOF FAILED for depth' \
          -e '^Failure node' \
          -e 'inferences so far.  Searching to depth' \
          -e '^val ' \
          -e 'Loading theory' \
          -e '^poly.*warning: The type of' \
          -e '^   monotype.$'
done
