#!/bin/bash

if [[ ! -n $TPTP ]]
then
  echo "TPTP environment variable is not set."
  exit 1
fi

slam_variant=$1
shift

echo Running sequentially: "$@"

for FILE in "$@"
do
  isabelle tptp_single 10 "$FILE" "slam" "$slam_variant"
done
